package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/DISCARDING.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /build/openjdk-8-fPix8r/openjdk-8-8u212-b03/src/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Friday, April 26, 2019 2:04:44 AM UTC
*/

public interface DISCARDING
{

  /** Object adapter state that causes all requests to be discarded.
     */
  public static final short value = (short)(2);
}
